/**
 * This code was generated by Builder.io.
 */
import * as React from 'react';
import { FormInputProps } from './types';

export const FormInput: React.FC<FormInputProps> = ({ label, placeholder, type = "text" }) => {
  const inputId = `${label.toLowerCase()}-input`;
  
  return (
    <div className="flex flex-col pb-4 w-full bg-white bg-opacity-0">
      <label htmlFor={inputId} className="flex gap-1 items-end pb-2 w-full bg-white bg-opacity-0 text-neutral-800">
        {label}
      </label>
      <div className="flex items-center w-full text-gray-500 rounded">
        <div className="flex overflow-hidden flex-1 shrink items-center self-stretch px-3 py-1.5 my-auto w-full bg-white rounded border border-gray-300 border-solid basis-0 min-w-[240px]">
          <input
            id={inputId}
            type={type}
            placeholder={placeholder}
            className="overflow-hidden flex-1 shrink gap-1 self-stretch my-auto w-full min-w-[240px] outline-none"
            aria-label={label}
          />
        </div>
      </div>
    </div>
  );
};