/**
 * This code was generated by Builder.io.
 */
import * as React from 'react';
import { FormInput } from './FormInput';

export const LoginPage: React.FC = () => {
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
  };

  return (
    <main className="flex overflow-hidden flex-col pb-96 bg-white max-w-[411px]">
      <img 
        loading="lazy" 
        src="https://cdn.builder.io/api/v1/image/assets/79d72f72cd3b4ad1b36630d32fe0aa9a/0025c6b8e05dd50e505ead667e8608594795285e0256b1bd6fd3bbe127622c35?apiKey=79d72f72cd3b4ad1b36630d32fe0aa9a&" 
        alt=""
        className="object-contain w-full rounded-none aspect-[1.31]" 
      />
      
      <form 
        onSubmit={handleSubmit}
        className="flex flex-col items-start self-center mt-10 max-w-full h-[196px] w-[343px]"
      >
        <section className="flex flex-col w-full text-xl whitespace-nowrap">
          <FormInput
            label="Email"
            placeholder="Johnsmith@mail.com"
            type="email"
          />
          <FormInput
            label="Password"
            placeholder="********************"
            type="password"
          />
        </section>

        <section className="flex flex-col items-center mt-7 w-full text-center max-w-[331px] min-h-[139px] shadow-[0px_4px_4px_rgba(0,0,0,0.25)]">
          <button
            type="submit"
            className="flex-1 shrink gap-2 px-6 py-4 max-w-full text-xl font-semibold leading-none text-white bg-red-900 rounded-md w-[300px]"
          >
            Sign In
          </button>
          <a 
            href="#" 
            className="mt-2.5 text-sm font-bold text-indigo-800"
            role="button"
            tabIndex={0}
          >
            Forgot Password?
          </a>
        </section>
      </form>
    </main>
  );
};